version: "3.3"

services:
  front.service:
    container_name: ojtracker-frontend
    build: ./
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - "3001:3001"
    tty: true
    stdin_open: true
