version: "3.3"

services:
  front.service:
    container_name: ojtracker-frontend
    build: ./
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
